name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      bump:
        description: "Semver bump to apply when preparing a release"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      custom_version:
        description: "Override version (takes precedence over bump); leave blank to auto-bump"
        required: false

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Prepare release
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PUBLISH_TOKEN }}

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install cargo-edit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit

      - name: Bump crate version
        id: bump
        env:
          BUMP: ${{ github.event.inputs.bump }}
          CUSTOM_VERSION: ${{ github.event.inputs.custom_version }}
        run: |
          set -euo pipefail

          if [[ -n "${CUSTOM_VERSION}" ]]; then
            echo "Setting version to ${CUSTOM_VERSION}"
            cargo set-version "${CUSTOM_VERSION}"
          else
            echo "Bumping version (${BUMP})"
            cargo set-version --bump "${BUMP}"
          fi

          version="$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.name == "hl") | .version')"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"

      - name: Run tests
        run: cargo test --locked

      - name: Commit and tag release
        env:
          VERSION: ${{ steps.bump.outputs.version }}
        run: |
          set -euo pipefail

          git status --short
          git commit -am "Release v${VERSION}"
          git tag -a "v${VERSION}" -m "Release v${VERSION}"

      - name: Push changes
        env:
          VERSION: ${{ steps.bump.outputs.version }}
        run: |
          set -euo pipefail

          current_branch="$(git rev-parse --abbrev-ref HEAD)"
          git push origin "${current_branch}"
          git push origin "v${VERSION}"

      - name: Release summary
        env:
          VERSION: ${{ steps.bump.outputs.version }}
        run: |
          {
            echo "## Release preparation complete"
            echo ""
            echo "- Version: v${VERSION}"
            echo "- Branch pushed: $(git rev-parse --abbrev-ref HEAD)"
            echo "- Tag pushed: v${VERSION}"
            echo ""
            echo "A new workflow run will build and publish release artifacts once the tag push is processed."
          } >> "${GITHUB_STEP_SUMMARY}"

  build:
    name: Build ${{ matrix.target }}
    if: github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_cross: true
          - os: macos-14
            target: aarch64-apple-darwin
            use_cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.use_cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Cache cargo directories
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-${{ matrix.target }}

      - name: Determine version
        id: version
        run: |
          ref="${GITHUB_REF_NAME}"
          version="${ref#v}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build binary
        run: |
          if [[ "${{ matrix.use_cross }}" == "true" ]]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Package archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p dist
          bin_path="target/${{ matrix.target }}/release/hl"
          archive="hl-${{ steps.version.outputs.version }}-${{ matrix.target }}.tar.gz"
          cp "$bin_path" dist/hl
          tar -C dist -czf "dist/${archive}" hl
          rm dist/hl

      - name: Package archive (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path dist -Force | Out-Null
          $BinPath = "target\${{ matrix.target }}\release\hl.exe"
          $Archive = "dist\hl-${{ steps.version.outputs.version }}-${{ matrix.target }}.zip"
          Copy-Item $BinPath "dist\hl.exe"
          Compress-Archive -Path "dist\hl.exe" -DestinationPath $Archive -Force
          Remove-Item "dist\hl.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hl-${{ steps.version.outputs.version }}-${{ matrix.target }}
          path: dist/*

  publish:
    name: Publish release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
